module.exports = [
  {
    firstName: "omar",
    lastName: null,
    phoneNumber: null,
    address: null,
    city: null,
    country: null,
    zipCode: null,
    email: "omar.admin@tiendamac.com",
    password: "tienda123.",
    image: null,
    externalSignIn: false,
    rol: "admin",
  },
  {
    firstName: "Daniel",
    lastName: null,
    phoneNumber: null,
    address: null,
    city: null,
    country: null,
    zipCode: null,
    email: "daniel.admin@tiendamac.com",
    password: "tienda123.",
    image: null,
    externalSignIn: false,
    rol: "admin",
  },
];