const allReviews = [
  {
    UserId: 1,
    ProductId: 1,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 2,
    score: 4,
    description: "los colores son lo mas!",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 3,
    score: 2,
    description: "se demoro bastante la entrega",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 4,
    score: 5,
    description: "excelente!",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 5,
    score: 5,
    description: "rápido y la calidad perfecta",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 6,
    score: 1,
    description: "no era lo que esperaba",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 7,
    score: 2,
    description: "se desgasto rápido",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 8,
    score: 4,
    description: "muy bien",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 9,
    score: 5,
    description: "",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 10,
    score: 3,
    description: "me parece que la tela podría ser de mejor calidad",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 11,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 12,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 13,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 14,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 15,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 16,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 17,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 18,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 19,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 20,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 21,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 22,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 23,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 24,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 25,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 26,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 27,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 28,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 29,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 30,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 31,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 32,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 33,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 34,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 35,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 36,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 37,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 38,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 39,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 40,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 41,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 42,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 43,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 44,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 45,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 46,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 47,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 48,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 49,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 50,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 51,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 52,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 53,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 54,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 55,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 56,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 57,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 58,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 59,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 60,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 61,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 62,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 63,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 64,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 1,
    ProductId: 65,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 66,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 1,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 2,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 3,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 4,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 5,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 6,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 7,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 8,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 9,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 10,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 11,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 12,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 13,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 14,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 15,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 16,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 17,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 18,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 19,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 20,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 21,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 22,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 23,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 24,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 25,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 26,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 27,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 28,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 29,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 30,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 31,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 32,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 33,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 34,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 35,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 36,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 37,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 38,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 39,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 40,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 41,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 42,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 43,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 44,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 45,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 46,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 47,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 48,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 49,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 50,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 51,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 52,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 53,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 54,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 55,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 56,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 57,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 58,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 59,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 60,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 61,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 62,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 63,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 64,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 65,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 2,
    ProductId: 66,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 1,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 2,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 3,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 4,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 5,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 6,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 7,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 8,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 9,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 10,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 11,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 12,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 13,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 14,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 15,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 16,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 17,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 18,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 19,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
  {
    UserId: 3,
    ProductId: 20,
    score: 5,
    description: "muy buen producto",
    status: "accepted",
  },
];
module.exports = allReviews;
